server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: uni-sys
    version: 0.0.1
  datasource:
    url: jdbc:h2:mem:${DB_NAME:demo}
    driver-class-name: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASS:12345678}
    hikari:
      auto-commit: false
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: dev

openapi:
  service:
    server: ${OPENAPI_SERVER:http://localhost:8080}
    title: Uni Sys
    version: 1.0.0
    description: API Documentation for Uni Sys
springdoc:
  swagger-ui:
    query-config-enabled: false
  api-docs:
    path: /api-docs-json

logging:
  level:
    root: warn
    org.springframework.web: debug
    org.hibernate: error
    org.hibernate.sql: OFF
    org.hibernate.type.descriptor.sql: OFF
  file:
    name: ${LOG_FILE:uni-sys.log}
    path: ${LOG_PATH:./logs}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000} # 1 day
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION:604800000} # 7 days
